"""Create portfolio analytics schema

Revision ID: 09eafbefeddc
Revises: 5218730555bb
Create Date: 2026-09-05 19:58:33.027843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09eafbefeddc'
down_revision: Union[str, Sequence[str], None] = '5218730555bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_asset_id'), 'prices', ['asset_id'], unique=False)
    op.create_index('ix_prices_asset_timestamp', 'prices', ['asset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_timestamp'), 'prices', ['timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_asset_id'), 'alerts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_portfolio_id'), 'alerts', ['portfolio_id'], unique=False)
    op.create_table('portfolio_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_return', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('benchmark_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('excess_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('benchmark_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_performance_date'), 'portfolio_performance', ['date'], unique=False)
    op.create_index(op.f('ix_portfolio_performance_id'), 'portfolio_performance', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_performance_portfolio_id'), 'portfolio_performance', ['portfolio_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('invested_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cumulative_return', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_snapshot_portfolio_date')
    )
    op.create_index(op.f('ix_portfolio_snapshots_id'), 'portfolio_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('risk_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('volatility', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('sortino_ratio', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('alpha', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('var_95', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('var_99', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('expected_shortfall', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_metrics_calculation_date'), 'risk_metrics', ['calculation_date'], unique=False)
    op.create_index(op.f('ix_risk_metrics_id'), 'risk_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_risk_metrics_portfolio_id'), 'risk_metrics', ['portfolio_id'], unique=False)
    op.create_table('stress_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('market_shock_percent', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('estimated_loss', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('estimated_loss_percent', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_tests_id'), 'stress_tests', ['id'], unique=False)
    op.create_index(op.f('ix_stress_tests_portfolio_id'), 'stress_tests', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_tests_portfolio_id'), table_name='stress_tests')
    op.drop_index(op.f('ix_stress_tests_id'), table_name='stress_tests')
    op.drop_table('stress_tests')
    op.drop_index(op.f('ix_risk_metrics_portfolio_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_id'), table_name='risk_metrics')
    op.drop_index(op.f('ix_risk_metrics_calculation_date'), table_name='risk_metrics')
    op.drop_table('risk_metrics')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_performance_portfolio_id'), table_name='portfolio_performance')
    op.drop_index(op.f('ix_portfolio_performance_id'), table_name='portfolio_performance')
    op.drop_index(op.f('ix_portfolio_performance_date'), table_name='portfolio_performance')
    op.drop_table('portfolio_performance')
    op.drop_index(op.f('ix_alerts_portfolio_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_prices_timestamp'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('ix_prices_asset_timestamp', table_name='prices')
    op.drop_index(op.f('ix_prices_asset_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
