"""Create holdings table

Revision ID: 5218730555bb
Revises: 00dbc7e7946f
Create Date: 2026-09-05 19:48:37.696023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5218730555bb'
down_revision: Union[str, Sequence[str], None] = '00dbc7e7946f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_asset_id'), 'holdings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_portfolio_id'), 'holdings', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_portfolio_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_asset_id'), table_name='holdings')
    op.drop_table('holdings')
    # ### end Alembic commands ###
